name: GI
on:
  push:
    branches:
      - "ghost-inspector-tests"
  pull_request:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: execute Ghost Inspector test
        uses: docker://ghostinspector/cli
        with:
          args: test execute ${{ secrets.GI_SUITE }} \
            --apiKey ${{ secrets.GI_API_KEY }} \
            --errorOnFail
